In [5]:
import pandas as pd
import numpy as np
data1 = pd.read_csv("/home/bladeray/Code/fintech/4/test_input_bal_uid_day7.txt", header=None)
d1 = data1.values

data2 = pd.read_csv("/home/bladeray/Code/fintech/4/test_input_bal_day7_uid_pre.txt", header=None)
d2 = data2.values


In [6]:
big = []
big_10_100 = []
dict_big = {}
dict_big_10_100 = {}
for i in range(len(d1)):
    if d1[i, -1] >= 5000000:
        big += [i]
        dict_big[int(d1[i, -2])] = 1
    if d1[i, -1] >= 100000 and d1[i, -1] <= 1000000:
        big_10_100 += [i]
        dict_big_10_100[int(d1[i, -2])] = 1
d1_reduce = np.delete(d1, big, 0)
X_train, y_train = d1[:, :-1], d1[:, -1]

In [32]:
for i in big:
    print(y_train[i])

5415161.27
5439924.85
5437246.01
5437634.06
5433463.07
5391131.94
5389609.55
5389356.4
5389870.65
5390507.5
5391183.8
5391244.58
5391199.32
5390719.19
5390719.19
5190883.98
5214790.13
5215160.06
5215143.84
5215066.18
5262457.18
6562286.34
6565834.75
6565798.29
6565793.29
6565911.16
6563202.73
6565367.13
6566999.72
6566999.72
6566999.72
6566999.72
6566999.72
6566725.92
6566725.92
6566725.92
6566925.11
6568836.37
6568708.45
6568708.45
6573434.66
6574060.49
6573294.03
6567410.65
6568439.22
6568289.03
6568289.03
6568564.1
6565113.4
6586459.59
6586121.79
6587189.72
6587184.72
6586976.48
6589092.99
6589238.59
6590792.14
6589870.57
6590482.64
6580185.64
6580185.64
6579817.79
6580054.08
6581919.25
6581998.23
6581161.95
6580848.45
5398674.85
5398674.81
5398674.81
5398674.81
5398674.84
5398274.8
5398274.75
5418966.13
5718666.06
5718666.06
5718666.1
5717666.14
5787597.95
5701525.44
5700637.44
5700637.44
5700637.44
5680637.44
5680637.44
5680637.44
5680637.44
5687228.99
5686622.33
5686622.33
568662

In [33]:
X_1, y_1 = d1_reduce[:, :-1], d1_reduce[:, -1]

In [34]:
d1_big = d1[big]

In [35]:
d1_big

array([[4.52703280e+06, 4.52692380e+06, 4.52632050e+06, ...,
        4.52827007e+06, 3.33000000e+02, 5.41516127e+06],
       [4.52692380e+06, 4.52632050e+06, 4.52632050e+06, ...,
        4.58017568e+06, 3.33000000e+02, 5.43992485e+06],
       [4.52632050e+06, 4.52632050e+06, 4.52868969e+06, ...,
        4.58052400e+06, 3.33000000e+02, 5.43724601e+06],
       ...,
       [1.67824148e+07, 1.67824148e+07, 1.67824148e+07, ...,
        1.68316489e+07, 4.06380000e+04, 1.68565312e+07],
       [1.67824148e+07, 1.67824148e+07, 1.68093980e+07, ...,
        1.68367700e+07, 4.06380000e+04, 1.68500506e+07],
       [1.67824148e+07, 1.68093980e+07, 1.68646720e+07, ...,
        1.68664896e+07, 4.06380000e+04, 1.68475534e+07]])

In [36]:
X_2, y_2 = d1_big[:, :-1], d1_big[:, -1]

In [37]:
print(len(X_2), len(y_train))

608 138000


In [38]:
X_1, y_1

(array([[5.0462780e+04, 5.0468620e+04, 5.0474470e+04, ..., 5.0497830e+04,
         5.0503660e+04, 5.0000000e+00],
        [5.0468620e+04, 5.0474470e+04, 5.0480310e+04, ..., 5.0503660e+04,
         5.0509440e+04, 5.0000000e+00],
        [5.0474470e+04, 5.0480310e+04, 5.0486150e+04, ..., 5.0509440e+04,
         5.3496240e+04, 5.0000000e+00],
        ...,
        [1.5430253e+05, 1.5430827e+05, 1.5431398e+05, ..., 1.5437271e+05,
         1.7469274e+05, 4.1594000e+04],
        [1.5430827e+05, 1.5431398e+05, 1.5432561e+05, ..., 1.7469274e+05,
         1.7412803e+05, 4.1594000e+04],
        [1.5431398e+05, 1.5432561e+05, 1.5434366e+05, ..., 1.7412803e+05,
         1.7413380e+05, 4.1594000e+04]]),
 array([  3508.94,   3509.31,   3509.69, ..., 174204.53, 174210.33,
        170716.13]))

In [39]:
y_train.shape

(138000,)

# RF

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
rf_reg = RandomForestRegressor(random_state=42)
param_grid = [
    # try  combinations of hyperparameters
    {'n_estimators': [100, 150, 200, 1000], 'max_features': [5, 6, 8]},
    # then try  combinations with bootstrap set as False
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
  ]

# train across 5 folds, that's a total of (12+6)*5=90 rounds of training 
grid_search = GridSearchCV(rf_reg, param_grid, cv=5,
                           scoring='neg_mean_absolute_error', return_train_score=True)
#Valid options are ['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']
grid_search.fit(X_train, y_train)
#y_pred_rf = rnd_clf.predict(X_test)

In [12]:
grid_search.best_params_

{'max_features': 6, 'n_estimators': 100}

In [14]:
grid_search.best_score_

-52319.229457316396

In [4]:
import xgboost as xgb

model = xgb.XGBRegressor(max_depth=5, learning_rate=0.1, n_estimators=160, silent=False, objective='reg:gamma')
model.fit(X_train, y_train)


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=160,
       n_jobs=1, nthread=None, objective='reg:gamma', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=False, subsample=1)

In [5]:
y_pre_xgb = model.predict(X_train)

In [6]:
y_pre_xgb, y_train

(array([ 48956.57 ,  48956.57 ,  50124.617, ..., 165392.55 , 175732.34 ,
        162515.62 ], dtype=float32),
 array([  3508.94,   3509.31,   3509.69, ..., 174204.53, 174210.33,
        170716.13]))

# 去除5000000 


In [40]:
import xgboost as xgb

model = xgb.XGBRegressor(max_depth=5, learning_rate=0.1, n_estimators=160, silent=False, objective='reg:gamma')
model.fit(X_1, y_1)
y_pre_xgb1 = model.predict(X_1)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_1, y_pre_xgb1)

44681.081161473514

# 5000000 

In [41]:
import xgboost as xgb

model = xgb.XGBRegressor(max_depth=200, learning_rate=0.1, n_estimators=500, silent=False, objective='reg:gamma')
model.fit(X_2[:,:-1], y_2)
y_pre_xgb2 = model.predict(X_2[:,:-1])
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_2, y_pre_xgb2)

10881.572138157919

In [42]:
import xgboost as xgb

model = xgb.XGBRegressor(learning_rate = 0.1, n_estimators = 1000, max_depth = 80, min_child_weight = 1, gamma = 0, subsample = 0.46,
        colsample_bytree = 0.8, objective = 'reg:gamma', nthread = 4, scale_pos_weight = 1, seed = 27)
model.fit(X_2, y_2)
y_pre_xgb2 = model.predict(X_2)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_2, y_pre_xgb2)

9847.879835526333

In [43]:
for i in range(len(y_2)):
    print((y_2[i], y_pre_xgb2[i]))

(5415161.27, 5415501.0)
(5439924.85, 5437485.0)
(5437246.01, 5437609.5)
(5437634.06, 5437122.0)
(5433463.07, 5432240.0)
(5391131.94, 5394172.0)
(5389609.55, 5389246.0)
(5389356.4, 5386399.5)
(5389870.65, 5388506.0)
(5390507.5, 5398608.5)
(5391183.8, 5392619.0)
(5391244.58, 5389287.5)
(5391199.32, 5391364.0)
(5390719.19, 5391662.5)
(5390719.19, 5389051.0)
(5190883.98, 5193098.0)
(5214790.13, 5215820.5)
(5215160.06, 5215542.0)
(5215143.84, 5215154.0)
(5215066.18, 5217631.5)
(5262457.18, 5261563.5)
(6562286.34, 6563464.5)
(6565834.75, 6564566.0)
(6565798.29, 6564178.0)
(6565793.29, 6566169.0)
(6565911.16, 6567659.5)
(6563202.73, 6560222.5)
(6565367.13, 6567810.0)
(6566999.72, 6564077.5)
(6566999.72, 6564766.5)
(6566999.72, 6570591.5)
(6566999.72, 6563802.5)
(6566999.72, 6566845.0)
(6566725.92, 6569701.5)
(6566725.92, 6566219.0)
(6566725.92, 6566306.5)
(6566925.11, 6567246.0)
(6568836.37, 6567985.0)
(6568708.45, 6568674.0)
(6568708.45, 6567772.0)
(6573434.66, 6570391.0)
(6574060.49, 657200

In [44]:
print(len(y_train) - len(y_2))

137392


In [45]:
big_flag = 0
y_train_xgb2 = y_train
j = 0
for i in big:
    print(i,  y_train[i] , y_pre_xgb2[j])
    y_train[i] = y_pre_xgb2[j]
    j += 1
print(y_train, y_train_xgb2)
mean_absolute_error(y_train, y_train_xgb2)

1313 5415161.27 5415501.0
1314 5439924.85 5437485.0
1315 5437246.01 5437609.5
1316 5437634.06 5437122.0
1317 5433463.07 5432240.0
1318 5391131.94 5394172.0
1319 5389609.55 5389246.0
1320 5389356.4 5386399.5
1321 5389870.65 5388506.0
1322 5390507.5 5398608.5
1323 5391183.8 5392619.0
1324 5391244.58 5389287.5
1325 5391199.32 5391364.0
1326 5390719.19 5391662.5
1327 5390719.19 5389051.0
1328 5190883.98 5193098.0
1329 5214790.13 5215820.5
1330 5215160.06 5215542.0
1331 5215143.84 5215154.0
1332 5215066.18 5217631.5
1333 5262457.18 5261563.5
24334 6562286.34 6563464.5
24335 6565834.75 6564566.0
24336 6565798.29 6564178.0
24337 6565793.29 6566169.0
24338 6565911.16 6567659.5
24339 6563202.73 6560222.5
24340 6565367.13 6567810.0
24341 6566999.72 6564077.5
24342 6566999.72 6564766.5
24343 6566999.72 6570591.5
24344 6566999.72 6563802.5
24345 6566999.72 6566845.0
24346 6566725.92 6569701.5
24347 6566725.92 6566219.0
24348 6566725.92 6566306.5
24349 6566925.11 6567246.0
24350 6568836.37 6567985.

95663 6533723.6 6542903.0
95664 6532723.6 6542903.0
95665 6589189.6 6542903.0
95666 6589241.41 6586753.0
95667 6589241.41 6592295.5
95668 6587141.41 6587104.5
95669 6580141.41 6581541.5
95670 6580141.41 6576258.5
95671 6580141.41 6580574.5
95672 6580141.41 6579734.0
95673 6580141.41 6580010.0
95674 6580141.41 6580763.0
95675 6580141.41 6581855.0
95676 6580141.41 6575631.5
95677 6580141.41 6579068.5
95678 6580141.41 6581415.5
95679 6580141.41 6579897.0
96751 5107658.18 5112606.0
96752 5112740.21 5110120.0
96753 5120653.35 5119505.0
96754 5119705.64 5121624.5
96755 5175087.19 5175714.5
96756 5180033.59 5177027.5
96757 5180035.34 5180445.0
96758 5180112.6 5182975.0
96759 5194702.73 5193336.0
96760 5194755.04 5193781.5
96761 5194755.04 5193841.0
96762 5194755.04 5195060.0
96763 5194755.04 5195060.0
96764 5194387.04 5195060.0
96765 5194387.04 5194762.5
96766 5194304.14 5195069.5
96767 5194304.14 5194455.5
96768 5194331.46 5193890.5
96769 5194624.25 5198866.0
96770 5202234.2 5202080.0
96771 

0.0

In [53]:
print(d2)

[[1.033431e+04 3.334670e+03 1.334800e+03 ... 1.335280e+03 1.335400e+03
  5.000000e+00]
 [6.032000e+03 6.032690e+03 6.033390e+03 ... 6.023860e+03 6.024550e+03
  1.500000e+01]
 [5.000000e+02 1.010000e+02 5.750000e+01 ... 9.102000e+01 7.046000e+03
  1.700000e+01]
 ...
 [0.000000e+00 0.000000e+00 0.000000e+00 ... 0.000000e+00 0.000000e+00
  4.114200e+04]
 [2.615200e+03 2.615200e+03 2.615200e+03 ... 2.105700e+03 2.105700e+03
  4.115500e+04]
 [2.988800e+02 2.988800e+02 2.988900e+02 ... 2.988900e+02 2.988900e+02
  4.115800e+04]]


In [57]:
print(dict_big)

{333: 1, 7105: 1, 7919: 1, 9760: 1, 12519: 1, 19058: 1, 19801: 1, 21132: 1, 28012: 1, 28148: 1, 28723: 1, 29057: 1, 29081: 1, 35028: 1, 35755: 1, 40638: 1}


In [59]:
pre_big = []
for i in range(len(d2)):
    if d2[i, -1] in dict_big.keys():
        pre_big += [i]
print(pre_big)
d2_pre = d2[pre_big]
y_pre = model.predict(d2_pre)

[28, 529, 586, 710, 908, 1393, 1437, 1523, 2032, 2043, 2079, 2103, 2105, 2564, 2611, 2953]


In [60]:
print(y_pre)

[ 5675386.   6583701.   5422767.5  6274212.  14365513.   6922675.
 13377851.   7568447.5  5171747.5  7074538.   6580411.5  5240311.
  6612608.5 96173120.   5449622.5 16862906. ]


In [7]:
d1_big_10_100 = d1[big_10_100]

In [8]:
d1_big_10_100

array([[6.4104410e+04, 6.4104410e+04, 2.5914090e+04, ..., 7.2345800e+03,
        3.8000000e+01, 1.1261497e+05],
       [6.4104410e+04, 2.5914090e+04, 2.2090900e+03, ..., 1.6920580e+04,
        3.8000000e+01, 1.4172997e+05],
       [1.3233849e+05, 1.3119933e+05, 1.2891479e+05, ..., 1.1955782e+05,
        1.4400000e+02, 1.1168453e+05],
       ...,
       [1.5430253e+05, 1.5430827e+05, 1.5431398e+05, ..., 1.7469274e+05,
        4.1594000e+04, 1.7420453e+05],
       [1.5430827e+05, 1.5431398e+05, 1.5432561e+05, ..., 1.7412803e+05,
        4.1594000e+04, 1.7421033e+05],
       [1.5431398e+05, 1.5432561e+05, 1.5434366e+05, ..., 1.7413380e+05,
        4.1594000e+04, 1.7071613e+05]])

In [9]:
X_3, y_3 = d1_big_10_100[:, :-1], d1_big_10_100[:, -1]

In [11]:
import xgboost as xgb

model3 = xgb.XGBRegressor(learning_rate = 0.1, n_estimators = 1000, max_depth = 80, min_child_weight = 1, gamma = 0, subsample = 0.46,
        colsample_bytree = 0.8, objective = 'reg:gamma', nthread = 4, scale_pos_weight = 1, seed = 27)
model3.fit(X_3, y_3)
y_pre_xgb3 = model3.predict(X_3)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_3, y_pre_xgb3)

826.7362349640521

In [12]:
print(dict_big_10_100)

{38: 1, 144: 1, 158: 1, 538: 1, 611: 1, 655: 1, 670: 1, 712: 1, 740: 1, 744: 1, 788: 1, 898: 1, 1021: 1, 1148: 1, 1184: 1, 1214: 1, 1233: 1, 1369: 1, 1616: 1, 1658: 1, 1694: 1, 1759: 1, 1763: 1, 1810: 1, 1829: 1, 1890: 1, 1943: 1, 2087: 1, 2090: 1, 2113: 1, 2221: 1, 2284: 1, 2297: 1, 2350: 1, 2352: 1, 2403: 1, 2478: 1, 2527: 1, 2572: 1, 2626: 1, 2806: 1, 2869: 1, 2880: 1, 2889: 1, 3003: 1, 3020: 1, 3090: 1, 3107: 1, 3110: 1, 3117: 1, 3142: 1, 3181: 1, 3200: 1, 3243: 1, 3463: 1, 3494: 1, 3530: 1, 3540: 1, 3661: 1, 3759: 1, 3879: 1, 3907: 1, 3922: 1, 4033: 1, 4091: 1, 4109: 1, 4147: 1, 4163: 1, 4241: 1, 4263: 1, 4333: 1, 4383: 1, 4503: 1, 4551: 1, 4583: 1, 4585: 1, 4665: 1, 4674: 1, 4735: 1, 4831: 1, 4859: 1, 4969: 1, 5075: 1, 5281: 1, 5284: 1, 5389: 1, 5407: 1, 5482: 1, 5505: 1, 5533: 1, 5575: 1, 5599: 1, 5622: 1, 5727: 1, 5743: 1, 5791: 1, 5865: 1, 5903: 1, 5929: 1, 6051: 1, 6113: 1, 6192: 1, 6219: 1, 6287: 1, 6303: 1, 6342: 1, 6377: 1, 6379: 1, 6406: 1, 6593: 1, 6629: 1, 6637: 1, 6704

In [14]:
print(len(dict_big_10_100), len(y_3))

672 21698


In [16]:
pre_big_10_100 = []
for i in range(len(d2)):
    if d2[i, -1] in dict_big_10_100.keys():
        pre_big_10_100 += [i]
print(pre_big_10_100, len(pre_big_10_100))
d2_pre_big_10_100 = d2[pre_big_10_100]
y_pre = model3.predict(d2_pre_big_10_100)

[4, 13, 14, 38, 45, 47, 48, 52, 55, 56, 59, 67, 72, 85, 87, 91, 92, 104, 116, 117, 121, 128, 129, 134, 138, 143, 149, 157, 158, 161, 169, 175, 176, 180, 182, 187, 188, 191, 194, 197, 213, 220, 221, 223, 231, 233, 237, 239, 240, 241, 244, 246, 249, 252, 266, 268, 269, 270, 282, 290, 294, 296, 297, 304, 309, 311, 314, 315, 320, 324, 326, 328, 333, 335, 337, 338, 344, 346, 351, 358, 360, 365, 373, 385, 386, 397, 398, 401, 402, 407, 409, 413, 416, 424, 427, 431, 439, 442, 444, 455, 460, 465, 467, 470, 471, 474, 475, 476, 478, 490, 493, 494, 499, 506, 511, 512, 514, 515, 516, 520, 525, 527, 534, 539, 544, 545, 546, 547, 551, 557, 558, 559, 569, 573, 574, 576, 577, 578, 579, 582, 590, 592, 593, 595, 597, 601, 603, 611, 619, 628, 630, 633, 636, 639, 643, 646, 654, 661, 662, 663, 674, 681, 682, 683, 688, 694, 696, 716, 721, 752, 753, 754, 760, 761, 763, 764, 773, 776, 781, 784, 785, 807, 808, 810, 814, 816, 833, 836, 838, 840, 841, 844, 847, 848, 850, 859, 861, 864, 868, 874, 875, 877, 882, 88

In [17]:
print(y_pre)

[162457.36  119400.08  255289.95  169639.6   507513.    205146.5
 160419.89  753573.1   317099.6   164539.23  142804.    822730.7
 280188.2   215117.2   157574.75  180127.7   140748.06  756756.3
 640431.75  335574.25  158503.77  216412.72  562740.5   190802.97
 174553.8   446116.38  178257.48  177918.16  442517.2   320535.3
 134170.38  214416.73  374686.56  239715.25  179274.94  605246.3
 218341.08  806111.6   208681.36  186468.36  162170.98  103499.03
 121982.13  132153.75  169882.77  636736.4   191438.72  143770.94
 127502.33  114954.34  806476.1   158434.84  418914.9   110546.51
 126656.164 117160.59  131875.52  246476.97  129332.46  216770.06
 151269.88  121448.414 647941.44  333345.94  559987.7   115363.99
 665303.8   598306.75  242958.56  119686.914 105291.445 130569.78
 182393.22  954664.7   511407.62  146073.16  741966.44  387472.88
 589000.56  104875.35  119593.81  246601.11  739427.75  183402.1
 113306.27  132220.31  116671.78  793473.25  132951.92  141924.77
 174061.08  3177

In [19]:
data3 = pd.read_csv("/home/bladeray/Code/fintech/4/out/test_input_bal_last.txt", header=None)
d3 = data3.values
y_train_xgb3 = d3
j = 0
for i in pre_big_10_100:
    print(i,  d3[i][3] , y_pre[j])
    y_train_xgb3[i][3] = y_pre[j]
    j += 1
    
mean_absolute_error(d3[:, 3], y_train_xgb3[:, 3])

4 8700.0 162457.36
13 35492.99 119400.08
14 270809.14 255289.95
38 180961.79 169639.6
45 505732.48 507513.0
47 201934.48 205146.5
48 157891.02 160419.89
52 759624.97 753573.1
55 313229.03 317099.6
56 1495.93 164539.23
59 0.05 142804.0
67 825903.25 822730.7
72 354529.16 280188.2
85 251988.88 215117.2
87 4876.19 157574.75
91 178275.95 180127.7
92 38197.85 140748.06
104 831084.93 756756.3
116 683017.92 640431.75
117 331458.15 335574.25
121 33406.53 158503.77
128 216751.33 216412.72
129 561728.08 562740.5
134 0.0 190802.97
138 11487.11 174553.8
143 444367.77 446116.38
149 10935.0 178257.48
157 172346.66 177918.16
158 454872.99 442517.2
161 320422.36 320535.3
169 135082.32 134170.38
175 17730.57 214416.73
176 383578.0 374686.56
180 231669.98 239715.25
182 225.33 179274.94
187 639655.05 605246.3
188 60867.05 218341.08
191 845710.63 806111.6
194 29476.42 208681.36
197 176694.01 186468.36
213 2327.84 162170.98
220 102721.39 103499.03
221 121931.26 121982.13
223 95176.7 132153.75
231 150176.04 

0.0

In [20]:
print(y_train_xgb3)

[[5 'bal' 81 1335.4]
 [15 'bal' 79 6024.55]
 [17 'bal' 78 7046.0]
 ...
 [41561 'bal' 77 1925.86]
 [41568 'bal' 72 14339.57]
 [41594 'bal' 83 204563.14]]


In [24]:
df = pd.DataFrame(y_train_xgb3) 
df.to_csv("/home/bladeray/Code/fintech/4/out/test_input_bal_last_4.txt", header=None, index=False)